import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './styles.css';
import './ipad-layout.css';
import './ending-video.css';
import './date-capsule.css';
const ModelPreview = React.lazy(() => import('./ModelPreview'));
const CouplePreview = React.lazy(() => import('./CouplePreview'));
const preview = new URLSearchParams(window.location.search).get('preview');
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode>{preview === 'couple' || preview === 'monchhichi' ? <React.Suspense fallback={<p className="preview-loading" role="status">กำลังเปิดโมเดล…</p>}>{preview === 'couple' ? <CouplePreview/> : <ModelPreview />}</React.Suspense> : <App />}</React.StrictMode>);
